language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install: pip install .
script: mictools --help
deploy:
  provider: pypi
  user: davidealbanese
  password:
    secure: QTY8dqEatEqqEkRIUcMp4xBP6bVv3wpn0/wClpVWY1eMSrrB6shcCLaPhdo6bB7BRmccGLJKG3TzAsoHqxEvlO/0yfuDbirCiNUutdOYkSJNEmiCYwpve2lER7otMStlnN04syJqNpC2seHB7UrT01tplH8woh60d7bosuZZ1aU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: minepy/mictools
