dist: xenial
sudo: true
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install: pip install .
script: mictools --help
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ot9Y8qh0oBkKmuVJwlwAIyOg8hWnRVYeO4pft5ZEUoul9NBN4wYqlenlqdCzeQnuX7Eba6ayePAGdrLdfHrTdFy3Iqs8834zDdF0Apd6C2jJLRKzrl9eZO2bdq1Iu5RMJZ7F4YwOBzRMN6lKbcJQRSyTlKWrFENbCFHjiKpOQ+jcVshFs9qFC0TgUXSPMC6WHn2iRLULNhyAo8kF2qIgxoSaEDoUYhZHpPyLVnlpitYX+yc8jJAtTA+uvTy72PpPtYdxEur5WUzJvfmSwAss1HEyEHI0KV1CHb76Fe3eBzu3QXqgi2GxXKxiuCnUyUXCEK8VJ6Ag0T7cZ0idoWooq2lmB7yMBG1qd4gCP+SKdSN//CNO3la7nR2DX7zmW7R1GCFqnQCOYEOgjWL5Nh4cPnr0qsIN9CpO5PwdxKKY+O7fQnmKld4F8MrHKOvweYyRbc6kvzWxiT/lRrAs2mwup4cAfkOo8KBZj1pwjY9l/DykexyAA7NiswQyc2Sj3tGq4ewxreFQIAgD2gR6kw+l8ttKlTXJRITo5Z5gkeNVAgBhPWIpco5ka03goqxWIiFEz4J21i2kohsVLQBU9i3YXgaY5CuJpS9xX4dDImym1CLsc5/gSZWFkUKmh/VUq14ksYGY3Gtc8wIm0NO3TTEg2+mfHFlxSiyG9uZMk/C7oYQ=
  skip_existing: true
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: minepy/mictools
