dist: xenial
sudo: true
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install: pip install .
script: mictools --help
deploy:
  provider: pypi
  user: davidealbanese
  password:
    secure: CXUYqQPJ/uNLev4bgkzT/aN528i3TbhqbdfDB1GtfSKtbKhsuVQAHRlYoCBUy8NZD3tktAylWgyCDohvndb8wI0fYc+IA3t3btIgUWxj92Q3XqLrK8I4tDWoJHDkdSTE6w4p/p/qhgQSQDpgOGvazfkIlWuJ8EWTlHrWkEAYa2vw1KmWe5lDdr0+B+8FeUcLxoWVZBJcY9QR3ImVQ8xoSi7c/oBhrAmMZYMjo/HDbnQxCEeQtdKRtS7LMTgdMPLCacwgVf9OatZugu58yQXW/Fmk+wBtrP3+115r1KpRDnBMk+3kTi1bvb5N/PwanpGO/HVWMS/bQKuAx+at6c41g0FHkLfSm4KTzRY+oUr9MvezsB2/Ps2kk+WapynwaVDfSwQ12Jf4eGqv6U8SxYDop71bJ0zRSLjWpOFP7j7FuBvRZPWSBINH6HQ5x/r7iyZz0QkDuRKoGiZOERzg/WHL1Pt3B24QFzvQkkNkAjm7Bfl4ChIJti9LhJIRk02Zccj1743Z1Wgx+x0q1QijSJFC5UR59YNzGje0If0qRrag0a4Z/5o7BLVN1KDQS/OKXZ5StUr0aDuajVwucogX/4jBohIRWOn9wFnja1o6dRdFYKtPGM6Gm8DWLgo0+150bHznaWLyvC4e76FvoV15aXFzVRY2z+zT6TKKPY/NhJHS0XE=
  skip_existing: true
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: minepy/mictools
